### ISSUE TITLE
flexible length prediction required

### ISSUE THREAD

**Issue by bigfeetsmalltone** [gaozhangyang/SimVP-Simpler-yet-Better-Video-Prediction#1]
The SimVP is set to produce a fixed-length sequence prediction whose length is the same as the input sequence's.

**Comment by gaozhangyang** [comment]
Thanks for your interest in this work. Denote the output length  and  input length as L_out and L_in respectively. If L_out<L_in, you can clip the output by output[:, :L_out,:,:]; otherwise you can repeatedly treat the output as input to get the future prediction:
```python

cnt = out_length // in_length
cur_seq = batch_x
pred_y = [] 
for patch in range(cnt):
      cur_seq = self.model(cur_seq)
      pred_y.append(cur_seq)
```

**Comment by bugsuse** [comment]
@gaozhangyang It's very interesting work! Could you release the example codes on the KTH dataset? This can help in understanding prediction tasks of different input and output lengths. Thanks a lot!
