### ISSUE TITLE
TaxiBJ results 

### ISSUE THREAD

**Issue by Mareeta26** [gaozhangyang/SimVP-Simpler-yet-Better-Video-Prediction#9]
Hi,
May I know whether you can share how you did the pre-processing and the post-processing of the TaxiBJ frames? It's stated int he paper " _Following [69], we transform the data into [0, 1] via max-min normalization. Since the origi- nal data is between -1 and 1, the reported MSE and MAE are 1/4 and 1/2 of the original ones, consistent with previous lit- erature_ ". It would be helpful if you can guide me. 

Thank you!

**Comment by gaozhangyang** [comment]
Suppose the original data is X, we use the transformed $\hat{X}$:

$\hat{X} = (X-X_{min}) / (X_{max}-X_{min})$,

where $X_{max}=1, X_{min}=-1$
